# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Anx/rtl_borad/fpga_top.xdc

# IP: ip/ila_0_1/ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet
