# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 8
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Anx/AnxBoard/AnxBoard/AnxBoard.cache/wt [current_project]
set_property parent.project_path D:/Anx/AnxBoard/AnxBoard/AnxBoard.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Anx/AnxBoard/AnxBoard/AnxBoard.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog D:/Anx/rtl_borad/mycpu.h
set_property file_type "Verilog Header" [get_files D:/Anx/rtl_borad/mycpu.h]
read_verilog -library xil_defaultlib {
  D:/Anx/rtl_borad/EXE.v
  D:/Anx/rtl_borad/ID.v
  D:/Anx/rtl_borad/IF.v
  D:/Anx/rtl_borad/MEM.v
  D:/Anx/rtl_borad/WB.v
  D:/Anx/rtl_borad/alu.v
  D:/Anx/rtl_borad/branch.v
  D:/Anx/rtl_borad/clog2.v
  D:/Anx/rtl_borad/controller.v
  D:/Anx/rtl_borad/data_ram.v
  D:/Anx/rtl_borad/decoder_2_4.v
  D:/Anx/rtl_borad/decoder_4_16.v
  D:/Anx/rtl_borad/decoder_5_32.v
  D:/Anx/rtl_borad/decoder_6_64.v
  D:/Anx/rtl_borad/divider.v
  D:/Anx/rtl_borad/exe_staller.v
  D:/Anx/rtl_borad/forward.v
  D:/Anx/rtl_borad/fpga_top.v
  D:/Anx/rtl_borad/imm.v
  D:/Anx/rtl_borad/inst_decode.v
  D:/Anx/rtl_borad/inst_ram.v
  D:/Anx/rtl_borad/mycpu_top.v
  D:/Anx/rtl_borad/op_decode.v
  D:/Anx/rtl_borad/regfile.v
  D:/Anx/rtl_borad/staller.v
  D:/Anx/rtl_borad/tb_fpga_top.v
  D:/Anx/rtl_borad/ila_test.v
}
read_ip -quiet d:/Anx/AnxBoard/AnxBoard/AnxBoard.srcs/sources_1/ip/ila_0_1/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/Anx/AnxBoard/AnxBoard/AnxBoard.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Anx/AnxBoard/AnxBoard/AnxBoard.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Anx/AnxBoard/AnxBoard/AnxBoard.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Anx/AnxBoard/AnxBoard/AnxBoard.srcs/sources_1/ip/ila_0_1/ila_0_ooc.xdc]

read_ip -quiet d:/Anx/AnxBoard/AnxBoard/AnxBoard.srcs/sources_1/ip/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all d:/Anx/AnxBoard/AnxBoard/AnxBoard.srcs/sources_1/ip/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all d:/Anx/AnxBoard/AnxBoard/AnxBoard.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Anx/rtl_borad/fpga_top.xdc
set_property used_in_implementation false [get_files D:/Anx/rtl_borad/fpga_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fpga_top -part xc7a35tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_top_utilization_synth.rpt -pb fpga_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
