# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Anx/AnxBoard/AnxBoard/AnxBoard.runs/synth_1/soc_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Anx/AnxBoard/AnxBoard/AnxBoard.cache/wt [current_project]
set_property parent.project_path D:/Anx/AnxBoard/AnxBoard/AnxBoard.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Anx/AnxBoard/AnxBoard/AnxBoard.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog D:/Anx/rtl_borad/mycpu.h
set_property file_type "Verilog Header" [get_files D:/Anx/rtl_borad/mycpu.h]
read_verilog -library xil_defaultlib {
  D:/Anx/rtl_borad/alu.v
  D:/Anx/rtl_borad/branch.v
  D:/Anx/rtl_borad/clog2.v
  D:/Anx/rtl_borad/controller.v
  D:/Anx/rtl_borad/data_ram.v
  D:/Anx/rtl_borad/decoder_2_4.v
  D:/Anx/rtl_borad/decoder_4_16.v
  D:/Anx/rtl_borad/decoder_5_32.v
  D:/Anx/rtl_borad/decoder_6_64.v
  D:/Anx/rtl_borad/divider.v
  D:/Anx/rtl_borad/exe_staller.v
  D:/Anx/rtl_borad/forward.v
  D:/Anx/rtl_borad/fpga_top.v
  D:/Anx/rtl_borad/imm.v
  D:/Anx/rtl_borad/inst_decode.v
  D:/Anx/rtl_borad/inst_ram.v
  D:/Anx/rtl_borad/op_decode.v
  D:/Anx/rtl_borad/regfile.v
  D:/Anx/rtl_borad/staller.v
  D:/Anx/rtl_borad/tb_fpga_top.v
  D:/Anx/rtl_borad/ila_test.v
  D:/Anx/rtl_borad/ID.v
  D:/Anx/rtl_borad/csr_register.v
  D:/Anx/rtl_borad/IF.v
  D:/Anx/rtl_borad/MEM.v
  D:/Anx/rtl_borad/interrupt.v
  D:/Anx/rtl_borad/trap_unit.v
  D:/Anx/rtl_borad/EXE.v
  D:/Anx/rtl_borad/mycpu_top.v
  D:/Anx/rtl_borad/WB.v
  D:/Anx/rtl_borad/soc_top.v
  D:/Anx/rtl_borad/tb_soc_top.v
  D:/Anx/rtl/ExE_reg.v
  D:/Anx/rtl/Wb_reg.v
  D:/Anx/rtl/data_ram_state.v
  D:/Anx/rtl/exe_allow_in_state.v
  D:/Anx/rtl/inst_ram_state.v
  D:/Anx/rtl/core_top.v
  D:/Anx/rtl/ID_stage.v
  D:/Anx/rtl/sram_axi_bridge.v
  D:/Anx/rtl/interrupt.v
  D:/Anx/rtl/ExE2_reg.v
  D:/Anx/rtl/id_allow_in_state.v
  D:/Anx/rtl/ID_readygo_state.v
  D:/Anx/rtl/exe2_allow_in_state.v
  D:/Anx/rtl/id_next_inst_cancel_state.v
  D:/Anx/rtl/csr.v
  D:/Anx/rtl/if_allow_in_state.v
  D:/Anx/rtl/mem_allow_in_state.v
  D:/Anx/rtl/IF_readygo_state.v
  D:/Anx/rtl/regfile.v
  D:/Anx/rtl/tlb.v
  D:/Anx/rtl/alu.v
  D:/Anx/rtl/EXE_readygo_state.v
  D:/Anx/rtl/Mem_reg.v
  D:/Anx/rtl/wb_stage.v
  D:/Anx/rtl/ID_REg.v
  D:/Anx/rtl/tb.v
  D:/Anx/rtl/pc_reg.v
  D:/Anx/rtl/tools.v
  D:/Anx/rtl/ExE1_reg.v
  D:/Anx/rtl/div.v
  D:/Anx/rtl/exe1_allow_in_state.v
  D:/Anx/rtl/EXE2_readygo_state.v
  D:/Anx/rtl/If_to_id_need_cancel.v
  D:/Anx/rtl/trap_unit.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Anx/rtl_borad/fpga_top.xdc
set_property used_in_implementation false [get_files D:/Anx/rtl_borad/fpga_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top soc_top -part xc7a200tfbg676-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_top_utilization_synth.rpt -pb soc_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
